clear all; close all; clc;

test = [0, 1; ...
        2, 1; ...
        2, 1.5; ...
        1.5, 0; ...
        0.5, 0.7; ...
        0.5, 2; ...
        1.5, 2.2 ];
% test = [0, 1; ...
%         2, 1; ...
%         1, 0; ...
%         1, 2; ...
%         0.015, 1+sqrt(0.029775) ];

[r_test,a_test,b_test] = CircleFit2D_MLS(test);
th = 0 : pi/50 : 2*pi;
th = th';
fittedCircle = [(r_test*cos(th) + a_test), (r_test*sin(th) + b_test)];

figure; hold on; grid on;
title('Test Circle Fit');
plot(test(:,1), test(:,2), 'ko');
plot(fittedCircle(:,1), fittedCircle(:,2), 'b-');
axis equal;
